# Generated by Django 4.2 on 2024-01-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foundation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="", max_length=120, verbose_name="foundation name")),
                ("address", models.CharField(default="0", max_length=100, verbose_name="Address of foundation")),
                ("email", models.CharField(default="0", max_length=100, verbose_name="Email of foundation")),
                ("phone_number", models.CharField(default="0", max_length=100, verbose_name="Phone of foundation")),
                ("logo", models.ImageField(null=True, upload_to="logos", verbose_name="Logo of foundation")),
                ("nit", models.CharField(default="0", max_length=9, verbose_name="Nit of foundation")),
                ("instagram", models.CharField(default="0", max_length=100, verbose_name="instagram of foundation")),
                ("twitter", models.CharField(default="0", max_length=100, verbose_name="twitter of foundation")),
                ("facebook", models.CharField(default="0", max_length=100, verbose_name="facebook of foundation")),
                (
                    "active_home_page",
                    models.BooleanField(
                        default=True,
                        help_text="Check to activate the home page. If not activated, the adoption page will be the home page.",
                        verbose_name="Activate home page?",
                    ),
                ),
                (
                    "active_about_page",
                    models.BooleanField(
                        default=True,
                        help_text="Check to activate the about page.",
                        verbose_name="Activate about page?",
                    ),
                ),
                (
                    "active_services_page",
                    models.BooleanField(
                        default=True,
                        help_text="Check to activate the services page.",
                        verbose_name="Activate services page?",
                    ),
                ),
                ("is_verify", models.BooleanField(default=False, verbose_name="Is verify foundation?")),
                ("adoption_fee", models.BooleanField(default=False, verbose_name="Adoption fee?")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountBank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="", max_length=120, verbose_name="Bank name")),
                ("number", models.CharField(default="", max_length=20, verbose_name="Bank account number")),
                ("qr", models.ImageField(blank=True, null=True, upload_to="qr_bank")),
                (
                    "foundation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="configuration.foundation"),
                ),
            ],
        ),
    ]
