# Generated by Django 4.2 on 2024-01-30 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RescuePet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name of Rescue Pet")),
                (
                    "species",
                    models.CharField(
                        choices=[("DG", "DOG"), ("CT", "CAT")], max_length=4, verbose_name="Specie of rescue pet"
                    ),
                ),
                ("gender", models.CharField(choices=[("M", "Male"), ("F", "Female")], max_length=1)),
                (
                    "age",
                    models.IntegerField(
                        help_text="Enter the age of rescue pet in years",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Age of rescue pet",
                    ),
                ),
                ("neutered", models.BooleanField(default=False, verbose_name="It's neutered?")),
                ("vaccinated", models.BooleanField(default=False, verbose_name="It's vaccinated")),
                (
                    "size",
                    models.CharField(
                        choices=[("B", "BIG"), ("M", "MEDIUM"), ("S", "SMALL")],
                        max_length=1,
                        verbose_name="Size rescue pet",
                    ),
                ),
                ("about", models.TextField(verbose_name="About rescue pet")),
                ("adoption_fee", models.BooleanField(default=False, verbose_name="Adoption fee?")),
                ("amount_adoption_fee", models.CharField(blank=True, null=True, verbose_name="Amount adoption fee")),
            ],
        ),
    ]
