# Generated by Django 4.2 on 2024-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rescuePet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rescuepet",
            name="adoption_fee",
        ),
        migrations.AlterField(
            model_name="rescuepet",
            name="amount_adoption_fee",
            field=models.CharField(blank=True, default="0", null=True, verbose_name="Amount adoption fee"),
        ),
    ]
