# Generated by Django 4.2 on 2024-01-31 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rescuePet", "0003_alter_rescuepet_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="RescuePetPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="rescuePet")),
                (
                    "rescuePet",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rescuePet.rescuepet"),
                ),
            ],
        ),
    ]
