# Generated by Django 4.2 on 2024-01-31 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rescuePet", "0005_rescuepet_adopted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rescuepetphoto",
            name="rescuePet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rescuePetPhoto", to="rescuePet.rescuepet"
            ),
        ),
    ]
