# Generated by Django 4.2 on 2024-01-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("foundation", "0002_foundation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundation",
            name="active_about_page",
            field=models.BooleanField(
                default=True, help_text="Check to activate the about page.", verbose_name="Activate about page?"
            ),
        ),
        migrations.AddField(
            model_name="foundation",
            name="active_home_page",
            field=models.BooleanField(
                default=True,
                help_text="Check to activate the home page. If not activated, the adoption page will be the home page.",
                verbose_name="Activate home page?",
            ),
        ),
        migrations.AddField(
            model_name="foundation",
            name="active_services_page",
            field=models.BooleanField(
                default=True, help_text="Check to activate the services page.", verbose_name="Activate services page?"
            ),
        ),
        migrations.AddField(
            model_name="foundation",
            name="address",
            field=models.CharField(default="0", max_length=100, verbose_name="Address of foundation"),
        ),
        migrations.AddField(
            model_name="foundation",
            name="email",
            field=models.CharField(default="0", max_length=100, verbose_name="Email of foundation"),
        ),
        migrations.AddField(
            model_name="foundation",
            name="facebook",
            field=models.CharField(default="0", max_length=100, verbose_name="facebook of foundation"),
        ),
        migrations.AddField(
            model_name="foundation",
            name="instagram",
            field=models.CharField(default="0", max_length=100, verbose_name="instagram of foundation"),
        ),
        migrations.AddField(
            model_name="foundation",
            name="is_verify",
            field=models.BooleanField(default=False, verbose_name="Is verify foundation?"),
        ),
        migrations.AddField(
            model_name="foundation",
            name="logo",
            field=models.ImageField(null=True, upload_to="tenant_img", verbose_name="Logo of foundation"),
        ),
        migrations.AddField(
            model_name="foundation",
            name="nit",
            field=models.CharField(default="0", max_length=9, verbose_name="Nit of foundation"),
        ),
        migrations.AddField(
            model_name="foundation",
            name="phone_number",
            field=models.CharField(default="0", max_length=100, verbose_name="Phone of foundation"),
        ),
        migrations.AddField(
            model_name="foundation",
            name="twitter",
            field=models.CharField(default="0", max_length=100, verbose_name="twitter of foundation"),
        ),
        migrations.CreateModel(
            name="AccountBank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="", max_length=120, verbose_name="Bank name")),
                ("number", models.CharField(default="", max_length=20, verbose_name="Bank account number")),
                ("qr", models.ImageField(upload_to="")),
                (
                    "foundation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="foundation.foundation"),
                ),
            ],
        ),
    ]
