# Generated by Django 4.2 on 2024-01-26 21:40

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):
    dependencies = [
        ("foundation", "0003_foundation_active_about_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain_url", models.CharField(max_length=128, unique=True)),
                (
                    "schema_name",
                    models.CharField(
                        max_length=63,
                        unique=True,
                        validators=[tenant_schemas.postgresql_backend.base._check_schema_name],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="foundation",
            name="domain_url",
        ),
        migrations.RemoveField(
            model_name="foundation",
            name="schema_name",
        ),
    ]
