# Generated by Django 4.2 on 2024-01-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foundation", "0004_tenant_remove_foundation_domain_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foundation",
            name="logo",
            field=models.ImageField(null=True, upload_to="carpetaintermediaaa", verbose_name="Logo of foundation"),
        ),
    ]
