# Generated by Django 4.2 on 2024-01-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foundation", "0007_alter_foundation_active_about_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foundation",
            name="active_about_page",
            field=models.BooleanField(
                default=True, help_text="Check to activate the about page.", verbose_name="Activate about page?"
            ),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="active_home_page",
            field=models.BooleanField(
                default=True,
                help_text="Check to activate the home page. If not activated, the adoption page will be the home page.",
                verbose_name="Activate home page?",
            ),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="active_services_page",
            field=models.BooleanField(
                default=True, help_text="Check to activate the services page.", verbose_name="Activate services page?"
            ),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="address",
            field=models.CharField(default="0", max_length=100, verbose_name="Address of foundation"),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="email",
            field=models.CharField(default="0", max_length=100, verbose_name="Email of foundation"),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="facebook",
            field=models.CharField(default="0", max_length=100, verbose_name="facebook of foundation"),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="instagram",
            field=models.CharField(default="0", max_length=100, verbose_name="instagram of foundation"),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="is_verify",
            field=models.BooleanField(default=False, verbose_name="Is verify foundation?"),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="name",
            field=models.CharField(default="", max_length=120, verbose_name="foundation name"),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="phone_number",
            field=models.CharField(default="0", max_length=100, verbose_name="Phone of foundation"),
        ),
        migrations.AlterField(
            model_name="foundation",
            name="twitter",
            field=models.CharField(default="0", max_length=100, verbose_name="twitter of foundation"),
        ),
    ]
