# Generated by Django 4.2 on 2024-01-30 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foundation", "0008_alter_foundation_active_about_page_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountBank",
        ),
        migrations.DeleteModel(
            name="Foundation",
        ),
    ]
