# Generated by Django 4.2 on 2024-01-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Add a title for show in banner", max_length=30, verbose_name="Title banner"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Add a short description for banner",
                        max_length=100,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "background_img",
                    models.ImageField(
                        help_text="Add a image for the background in banner",
                        upload_to="banner",
                        verbose_name="Image background",
                    ),
                ),
                (
                    "button_message",
                    models.CharField(
                        blank=True,
                        help_text="Add a call to action message",
                        max_length=13,
                        null=True,
                        verbose_name="Button message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Title for section services", verbose_name="Title service section"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description services section", verbose_name="Description services section"
                    ),
                ),
                ("image", models.ImageField(upload_to="service-section", verbose_name="Image for services section")),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title for services", verbose_name="Title service")),
                (
                    "description",
                    models.TextField(help_text="Description services ", verbose_name="Description services "),
                ),
                (
                    "icon",
                    models.CharField(help_text="Select icon for services", max_length=100, verbose_name="Select Icon"),
                ),
                (
                    "serviceInfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="services", to="portal.serviceinfo"
                    ),
                ),
            ],
        ),
    ]
